name: Deploy to Hostinger
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [reportarai.com]    branches: [ main ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.HOSTINGER_SERVER }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        password: ${{ secrets.HOSTINGER_PASSWORD }}
        server-dir: public_html/
